;class Opacity extends Visualization{

  // update options
  update_options (opt = {}) {
    this.options = $.extend({
      'gap':                30,
    }, this.options)
  }

  // update default dataset
  update_data (dat = null) {
    if (this.options.data == null){
      this.options.data = [
        [
          {"label": "1",
          "value":14,},
          {"label": "2",
          "value":17,},
          {"label": "3",
          "value":9,},
          {"label": "4",
          "value":9,},
          {"label": "5",
          "value":14,},
          {"label": "6",
          "value":10,},
          {"label": "7",
          "value":11,},
          {"label": "8",
          "value":21,},
          {"label": "9",
          "value":33,},
          {"label": "10",
          "value": 48,},
          {"label": "11",
          "value": 50,},
          {"label": "12",
          "value": 18,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":14,},
          {"label": "2",
          "value":9,},
          {"label": "3",
          "value":17,},
          {"label": "4",
          "value":22,},
          {"label": "5",
          "value":7,},
          {"label": "6",
          "value":11,},
          {"label": "7",
          "value":10,},
          {"label": "8",
          "value":12,},
          {"label": "9",
          "value":22,},
          {"label": "10",
          "value": 35,},
          {"label": "11",
          "value": 46,},
          {"label": "12",
          "value": 29,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":6,},
          {"label": "2",
          "value":19,},
          {"label": "3",
          "value":11,},
          {"label": "4",
          "value":9,},
          {"label": "5",
          "value":15,},
          {"label": "6",
          "value":13,},
          {"label": "7",
          "value":12,},
          {"label": "8",
          "value":42,},
          {"label": "9",
          "value":48,},
          {"label": "10",
          "value": 43,},
          {"label": "11",
          "value": 46,},
          {"label": "12",
          "value": 42,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":14,},
          {"label": "2",
          "value":9,},
          {"label": "3",
          "value":8,},
          {"label": "4",
          "value":17,},
          {"label": "5",
          "value":8,},
          {"label": "6",
          "value":22,},
          {"label": "7",
          "value":10,},
          {"label": "8",
          "value":27,},
          {"label": "9",
          "value":39,},
          {"label": "10",
          "value": 34,},
          {"label": "11",
          "value": 34,},
          {"label": "12",
          "value": 34,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":8,},
          {"label": "2",
          "value":15,},
          {"label": "3",
          "value":8,},
          {"label": "4",
          "value":5,},
          {"label": "5",
          "value":4,},
          {"label": "6",
          "value":11,},
          {"label": "7",
          "value":8,},
          {"label": "8",
          "value":19,},
          {"label": "9",
          "value":40,},
          {"label": "10",
          "value": 37,},
          {"label": "11",
          "value": 45,},
          {"label": "12",
          "value": 12,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":12,},
          {"label": "2",
          "value":10,},
          {"label": "3",
          "value":18,},
          {"label": "4",
          "value":5,},
          {"label": "5",
          "value":7,},
          {"label": "6",
          "value":3,},
          {"label": "7",
          "value":5,},
          {"label": "8",
          "value":22,},
          {"label": "9",
          "value":30,},
          {"label": "10",
          "value": 35,},
          {"label": "11",
          "value": 22,},
          {"label": "12",
          "value": 18,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ],
        [
          {"label": "1",
          "value":11,},
          {"label": "2",
          "value":10,},
          {"label": "3",
          "value":4,},
          {"label": "4",
          "value":5,},
          {"label": "5",
          "value":2,},
          {"label": "6",
          "value":4,},
          {"label": "7",
          "value":21,},
          {"label": "8",
          "value":23,},
          {"label": "9",
          "value":43,},
          {"label": "10",
          "value": 35,},
          {"label": "11",
          "value": 35,},
          {"label": "12",
          "value": 16,},
          {"label": "13",
          "value": 0,},
          {"label": "14",
          "value": 0,},
          {"label": "15",
          "value": 0,},
          {"label": "16",
          "value": 0,},
          {"label": "17",
          "value": 0,},
          {"label": "18",
          "value": 0,},
          {"label": "19",
          "value": 0,},
          {"label": "20",
          "value": 0,},
          {"label": "21",
          "value": 0,},
          {"label": "22",
          "value": 0,},
          {"label": "23",
          "value": 0,},
          {"label": "24",
          "value": 0},
        ]
      ]
    }
  }

  // visaulization
  draw_visualization (size, vm) {
    var svg       = vm.wrap,
        dataset   = vm.data,
        width     = size[0],
        height    = size[1],
        gap       = vm.gap;


    var _max = d3.max(_.map(dataset, function(d){
      var temp = d3.max(d, function(_d){ return _d.value})
      return temp
    }))
    var _min = d3.min(_.map(dataset, function(d){
      var temp = d3.min(d, function(_d){ return _d.value})
      return temp
    }))

    var norm = d3.scale.linear()
      .domain([_min, _max])
      .range([0.1,1])

    var nodes = []
    _.each(dataset, function(_d,_i){
      _.each(_d, function(d,i){
        nodes.push({
          "x": (width / 2) + (gap * i) - (gap * dataset[0].length / 2),
          "y": (height / 2) + (gap * _i) - (gap * dataset.length / 2),
          "text": d.label,
          "value": d.value
        })
      })
    })

    var node = svg.selectAll("text")
      .data(nodes).enter()
      .append("text")
      .text(function(d){ return d.text})
      .style("text-anchor", "middle")
      .attr("transform", function(d){ return "translate("+d.x+","+d.y+")"})
      .attr("transform", function(d){ return "translate("+d.x+","+d.y+")"})
      .attr("opacity", function(d){ return norm(d.value) })

  }

}
